python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU --K 3
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 3, 'fig': False}
Solver Time: 1593.5623366250002
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 1150
True Negatives (TN): 1150
False Negatives (FN): 0
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 41, in main
    precision,recall,f_score,accuracy = utils.compute_metrics(_SVM,alpha,data,t,b,args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/utils.py", line 83, in compute_metrics
    recall = tp / (tp + fn)
ZeroDivisionError: division by zero
python3 Main.py --dataFile planet --trainingPoints 1100 --validationPoints 650 --type HQPU --K 3 --B 3
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 1100, 'validationPoints': 650, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 3, 'K': 3, 'fig': False}
Solver Time: 68.409741625
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:95: RuntimeWarning: overflow encountered in scalar multiply
  b = sum([alpha[n]*(self.C-alpha[n])*(t[n]-(sum([alpha[m]*t[m]*self.kernel(data[m], data[n])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar multiply
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 325
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 325
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 1100 --validationPoints 750 --type HQPU --K 3 --B 3
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 1100, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 3, 'K': 3, 'fig': False}
Solver Time: 68.332353375
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:95: RuntimeWarning: overflow encountered in scalar multiply
  b = sum([alpha[n]*(self.C-alpha[n])*(t[n]-(sum([alpha[m]*t[m]*self.kernel(data[m], data[n])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar multiply
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 375
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 375
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 2100 --validationPoints 1250 --type HQPU --K 3 --B 3
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 2100, 'validationPoints': 1250, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 3, 'K': 3, 'fig': False}
Solver Time: 243.380413541
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:95: RuntimeWarning: overflow encountered in scalar multiply
  b = sum([alpha[n]*(self.C-alpha[n])*(t[n]-(sum([alpha[m]*t[m]*self.kernel(data[m], data[n])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar multiply
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 625
True Negatives (TN): 625
False Negatives (FN): 0
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 41, in main
    precision,recall,f_score,accuracy = utils.compute_metrics(_SVM,alpha,data,t,b,args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/utils.py", line 83, in compute_metrics
    recall = tp / (tp + fn)
ZeroDivisionError: division by zero
python3 Main.py --dataFile planet --trainingPoints 2100 --validationPoints 1250 --type HQPU --K 1 --B 1
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 2100, 'validationPoints': 1250, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 1, 'K': 1, 'fig': False}
Solver Time: 27.684323582999998
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 544
False Positives (FP): 81
True Negatives (TN): 612
False Negatives (FN): 13
precision=0.8704 recall=0.9766606822262118 f_score=0.9204737732656514 accuracy=0.9248
python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU --K 1 --B 1
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 1, 'K': 1, 'fig': False}
Solver Time: 161.07408262500002
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1150
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 1150
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 2100 --validationPoints 1250 --type HQPU --K 1.5 --B 1.5
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
usage: Main.py [-h] [--type {SA,HQPU,QPU}] [--dataFile DATAFILE] [--trainingPoints TRAININGPOINTS] [--validationPoints VALIDATIONPOINTS] [--C C] [--xi XI]
               [--gamma GAMMA] [--B B] [--K K] [--fig]
Main.py: error: argument --K: invalid int value: '1.5'
python3 Main.py --dataFile planet --trainingPoints 2100 --validationPoints 1250 --type HQPU --xi 0.002
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
usage: Main.py [-h] [--type {SA,HQPU,QPU}] [--dataFile DATAFILE] [--trainingPoints TRAININGPOINTS] [--validationPoints VALIDATIONPOINTS] [--C C] [--xi XI]
               [--gamma GAMMA] [--B B] [--K K] [--fig]
Main.py: error: argument --xi: invalid int value: '0.002'
python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.005, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 672.016393208
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 1150
True Negatives (TN): 1150
False Negatives (FN): 0
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 41, in main
    precision,recall,f_score,accuracy = utils.compute_metrics(_SVM,alpha,data,t,b,args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/utils.py", line 83, in compute_metrics
    recall = tp / (tp + fn)
ZeroDivisionError: division by zero
python3 Main.py --dataFile planet_pca_stand --trainingPoints 1000 --validationPoints 200 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 1000, 'validationPoints': 200, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 24.813869792
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 36, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 89, in train_SVM
    a = response.first.sample
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1085, in first
    return next(self.data(sorted_by='energy', name='Sample'))
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1277, in data
    record = self.record
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1126, in record
    self.resolve()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1490, in resolve
    samples = self._result_hook(self._future)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 833, in <lambda>
    sampleset = dimod.SampleSet.from_future(self, lambda f: f.wait_sampleset())
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 771, in wait_sampleset
    self._load_result()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 907, in _load_result
    raise self._exception
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/client/base.py", line 1341, in _handle_problem_status
    raise SolverFailureError(message['error_msg'])
dwave.cloud.exceptions.SolverFailureError: Attempting to run a problem for less than the allowed minimum time_limit 5.223958333333334 s.
python3 Main.py --dataFile planet_pca_stand --trainingPoints 2000 --validationPoints 200 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 2000, 'validationPoints': 200, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 100.53490612499999
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 100
False Positives (FP): 0
True Negatives (TN): 3
False Negatives (FN): 97
precision=1.0 recall=0.5076142131979695 f_score=0.6734006734006734 accuracy=0.515
python3 Main.py --dataFile planet_pca_stand --trainingPoints 2000 --validationPoints 500 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 2000, 'validationPoints': 500, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 103.31870166700001
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 250
False Positives (FP): 0
True Negatives (TN): 6
False Negatives (FN): 244
precision=1.0 recall=0.5060728744939271 f_score=0.6720430107526881 accuracy=0.512
python3 Main.py --dataFile planet_pca_stand --trainingPoints 2000 --validationPoints 1000 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 2000, 'validationPoints': 1000, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 97.6213295
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 500
False Positives (FP): 0
True Negatives (TN): 9
False Negatives (FN): 491
precision=1.0 recall=0.5045408678102926 f_score=0.670690811535882 accuracy=0.509
python3 Main.py --dataFile planet_pca_stand --trainingPoints 200 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 200, 'validationPoints': 100, 'C': 3, 'xi': 0.01, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 3.7638665000000002
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 50
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 50
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet_pca_stand --trainingPoints 200 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 200, 'validationPoints': 100, 'C': 3, 'xi': 0.1, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 3.840743667
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 50
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 50
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet_pca_stand --trainingPoints 200 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_pca_stand', 'trainingPoints': 200, 'validationPoints': 100, 'C': 3, 'xi': 10, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 3.7118220830000004
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 50
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 50
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 200 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 200, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 3.804123791
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 50
True Negatives (TN): 0
False Negatives (FN): 50
precision=0.0 recall=0.0 f_score=0.0 accuracy=0.0
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.72446725
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 50
True Negatives (TN): 1
False Negatives (FN): 49
precision=0.0 recall=0.0 f_score=0.0 accuracy=0.01
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.698426542
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 50
True Negatives (TN): 1
False Negatives (FN): 49
precision=0.0 recall=0.0 f_score=0.0 accuracy=0.01
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.691475125
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 49
False Positives (FP): 1
True Negatives (TN): 34
False Negatives (FN): 16
precision=0.98 recall=0.7538461538461538 f_score=0.8521739130434782 accuracy=0.83
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.672405125000001
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 49
False Positives (FP): 1
True Negatives (TN): 35
False Negatives (FN): 15
precision=0.98 recall=0.765625 f_score=0.8596491228070176 accuracy=0.84
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 100 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 100, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.524645374999999
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 50
False Positives (FP): 0
True Negatives (TN): 12
False Negatives (FN): 38
precision=1.0 recall=0.5681818181818182 f_score=0.7246376811594203 accuracy=0.62
python3 Main.py --dataFile planet --trainingPoints 500 --validationPoints 300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 500, 'validationPoints': 300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 12.617280417
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 150
False Positives (FP): 0
True Negatives (TN): 39
False Negatives (FN): 111
precision=1.0 recall=0.5747126436781609 f_score=0.7299270072992701 accuracy=0.63
python3 Main.py --dataFile planet --trainingPoints 5000 --validationPoints 2000 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5000, 'validationPoints': 2000, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 689.811256
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1000
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 1000
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 1000 --validationPoints 500 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 1000, 'validationPoints': 500, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 26.995608958000002
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 36, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 89, in train_SVM
    a = response.first.sample
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1085, in first
    return next(self.data(sorted_by='energy', name='Sample'))
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1277, in data
    record = self.record
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1126, in record
    self.resolve()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1490, in resolve
    samples = self._result_hook(self._future)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 833, in <lambda>
    sampleset = dimod.SampleSet.from_future(self, lambda f: f.wait_sampleset())
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 771, in wait_sampleset
    self._load_result()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 907, in _load_result
    raise self._exception
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/client/base.py", line 1341, in _handle_problem_status
    raise SolverFailureError(message['error_msg'])
dwave.cloud.exceptions.SolverFailureError: Attempting to run a problem for less than the allowed minimum time_limit 5.223958333333334 s.
python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 668.735068166
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1150
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 1150
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 673.678633166
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1139
False Positives (FP): 11
True Negatives (TN): 582
False Negatives (FN): 568
precision=0.9904347826086957 recall=0.667252489748096 f_score=0.7973398669933497 accuracy=0.7482608695652174
python3 Main.py --dataFile planet --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 665.602778125
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 875
False Positives (FP): 275
True Negatives (TN): 1126
False Negatives (FN): 24
precision=0.7608695652173914 recall=0.9733036707452726 f_score=0.854075158613958 accuracy=0.87
python3 Main.py --dataFile planet_corr_9 --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_9', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 661.21096475
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 0
False Positives (FP): 581
True Negatives (TN): 1719
False Negatives (FN): 0
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 41, in main
    precision,recall,f_score,accuracy = utils.compute_metrics(_SVM,alpha,data,t,b,args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/utils.py", line 83, in compute_metrics
    recall = tp / (tp + fn)
ZeroDivisionError: division by zero
python3 Main.py --dataFile planet_corr_9 --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_9', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 674.689273167
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1150
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 1150
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet_corr_5 --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_5', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 647.759549042
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1150
False Positives (FP): 0
True Negatives (TN): 0
False Negatives (FN): 1150
precision=1.0 recall=0.5 f_score=0.6666666666666666 accuracy=0.5
python3 Main.py --dataFile planet_corr_3 --trainingPoints 1000 --validationPoints 500 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_3', 'trainingPoints': 1000, 'validationPoints': 500, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 25.615042542000005
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 36, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 89, in train_SVM
    a = response.first.sample
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1085, in first
    return next(self.data(sorted_by='energy', name='Sample'))
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1277, in data
    record = self.record
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1126, in record
    self.resolve()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1490, in resolve
    samples = self._result_hook(self._future)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 833, in <lambda>
    sampleset = dimod.SampleSet.from_future(self, lambda f: f.wait_sampleset())
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 771, in wait_sampleset
    self._load_result()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 907, in _load_result
    raise self._exception
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/client/base.py", line 1341, in _handle_problem_status
    raise SolverFailureError(message['error_msg'])
dwave.cloud.exceptions.SolverFailureError: Attempting to run a problem for less than the allowed minimum time_limit 5.223958333333334 s.
python3 Main.py --dataFile planet_corr_3 --trainingPoints 1500 --validationPoints 750 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_3', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 53.327339083
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 375
False Positives (FP): 0
True Negatives (TN): 7
False Negatives (FN): 368
precision=1.0 recall=0.5047106325706595 f_score=0.6708407871198568 accuracy=0.5093333333333333
python3 Main.py --dataFile planet_corr_3 --trainingPoints 1500 --validationPoints 750 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_3', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
^CTraceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 36, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 75, in train_SVM
    qubo = {(i, j): Q[i, j]
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 75, in <dictcomp>
    qubo = {(i, j): Q[i, j]
KeyboardInterrupt

python3 Main.py --dataFile planet_corr_3 --trainingPoints 1500 --validationPoints 750 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_3', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 34, in main
    data,t = DataLoader.load_data(args['dataFile'],args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/DataLoader.py", line 7, in load_data
    training_data = np.loadtxt('./data/{}.txt'.format(data_file), delimiter=',')\
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_npyio_impl.py", line 1381, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_npyio_impl.py", line 997, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_datasource.py", line 192, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./data/planet_corr_3.txt not found.
python3 Main.py --dataFile planet_corr_4 --trainingPoints 1500 --validationPoints 750 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
Solver Time: 54.759434125000006
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:96: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 373
False Positives (FP): 2
True Negatives (TN): 7
False Negatives (FN): 368
precision=0.9946666666666667 recall=0.5033738191632928 f_score=0.6684587813620072 accuracy=0.5066666666666667
python3 Main.py --dataFile planet_corr_4 --trainingPoints 5100 --validationPoints 2300 --type HQPU
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False}
^CTraceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 46, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 36, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 63, in train_SVM
    Q_tilde[(self.K*n+k, self.K*m+j)] = 0.5*(self.B**(k+j))*t[n]*t[m] * \
KeyboardInterrupt

python3 Main.py --dataFile planet_corr_4 --trainingPoints 1500 --validationPoints 750 --type HQPU --label "try label"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'try label'}
Solver Time: 57.126409709
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 373
False Positives (FP): 2
True Negatives (TN): 7
False Negatives (FN): 368
precision=0.9946666666666667 recall=0.5033738191632928 f_score=0.6684587813620072 accuracy=0.5066666666666667
python3 Main.py --dataFile planet_corr_4 --trainingPoints 5100 --validationPoints 2300 --type HQPU --label "corr 4 all data"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 5100, 'validationPoints': 2300, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'corr 4 all data'}
Solver Time: 646.286824458
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 1150
False Positives (FP): 0
True Negatives (TN): 25
False Negatives (FN): 1125
precision=1.0 recall=0.5054945054945055 f_score=0.6715328467153284 accuracy=0.5108695652173914
python3 Main.py --dataFile planet_corr_4 --trainingPoints 1500 --validationPoints 750 --type HQPU --label "try label"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'try label'}
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 47, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 35, in main
    data,t = DataLoader.load_data(args['dataFile'],args['trainingPoints'],args['validationPoints'])
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/DataLoader.py", line 7, in load_data
    training_data = np.loadtxt('./data/{}.txt'.format(data_file), delimiter=',')\
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_npyio_impl.py", line 1381, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_npyio_impl.py", line 997, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_datasource.py", line 192, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ./data/planet_corr_4.txt not found.
python3 Main.py --dataFile planet_corr_4 --trainingPoints 1500 --validationPoints 750 --type HQPU --label "corr4 2000 standardized"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'corr4 2000 standardized'}
Solver Time: 57.914714333000006
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 355
False Positives (FP): 20
True Negatives (TN): 362
False Negatives (FN): 13
precision=0.9466666666666667 recall=0.9646739130434783 f_score=0.955585464333782 accuracy=0.956
python3 Main.py --dataFile planet_corr_4 --trainingPoints 4000 --validationPoints 1750 --type HQPU --label "corr4 5000 standardized"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_4', 'trainingPoints': 4000, 'validationPoints': 1750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'corr4 5000 standardized'}
Solver Time: 395.561367416
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 830
False Positives (FP): 45
True Negatives (TN): 819
False Negatives (FN): 56
precision=0.9485714285714286 recall=0.9367945823927766 f_score=0.9426462237365133 accuracy=0.9422857142857143
python3 Main.py --dataFile planet_corr_9 --trainingPoints 4000 --validationPoints 1750 --type HQPU --label "corr4 5000 standardized"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_corr_9', 'trainingPoints': 4000, 'validationPoints': 1750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'corr4 5000 standardized'}
Solver Time: 398.2477430839999
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 834
False Positives (FP): 41
True Negatives (TN): 814
False Negatives (FN): 61
precision=0.9531428571428572 recall=0.9318435754189944 f_score=0.9423728813559322 accuracy=0.9417142857142857
python3 Main.py --dataFile planet_stand01 --trainingPoints 1500 --validationPoints 750 --type HQPU --label "all features - stand"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_stand01', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'all features - stand'}
Solver Time: 54.235186875
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 352
False Positives (FP): 23
True Negatives (TN): 358
False Negatives (FN): 17
precision=0.9386666666666666 recall=0.9539295392953929 f_score=0.946236559139785 accuracy=0.9466666666666667
python3 Main.py --dataFile planet_stand01 --trainingPoints 1500 --validationPoints 750 --type HQPU --label "all features 36 - stand"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_stand01', 'trainingPoints': 1500, 'validationPoints': 750, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'all features 36 - stand'}
Solver Time: 60.797626292000004
/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py:97: RuntimeWarning: overflow encountered in scalar add
  for m in range(self.N)]))) for n in range(self.N)])/sum([alpha[n]*(self.C-alpha[n]) for n in range(self.N)])
True Positives (TP): 103
False Positives (FP): 272
True Negatives (TN): 375
False Negatives (FN): 0
precision=0.27466666666666667 recall=1.0 f_score=0.4309623430962343 accuracy=0.6373333333333333
python3 Main.py --dataFile planet_stand01 --trainingPoints 3500 --validationPoints 1500 --type HQPU --label "all features 3500 - stand"
/Users/smenn/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
{'type': 'HQPU', 'dataFile': 'planet_stand01', 'trainingPoints': 3500, 'validationPoints': 1500, 'C': 3, 'xi': 0.001, 'gamma': 16, 'B': 2, 'K': 2, 'fig': False, 'label': 'all features 3500 - stand'}
Solver Time: 305.80767012499996
Traceback (most recent call last):
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 47, in <module>
    main()
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/Main.py", line 37, in main
    alpha, b = _SVM.train_SVM(data, t)
  File "/Users/smenn/Research/QML/QML-Project/qubo-svm/svm.py", line 90, in train_SVM
    a = response.first.sample
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1085, in first
    return next(self.data(sorted_by='energy', name='Sample'))
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1277, in data
    record = self.record
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1126, in record
    self.resolve()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dimod/sampleset.py", line 1490, in resolve
    samples = self._result_hook(self._future)
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 833, in <lambda>
    sampleset = dimod.SampleSet.from_future(self, lambda f: f.wait_sampleset())
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 771, in wait_sampleset
    self._load_result()
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/computation.py", line 907, in _load_result
    raise self._exception
  File "/Users/smenn/Library/Python/3.9/lib/python/site-packages/dwave/cloud/client/base.py", line 1341, in _handle_problem_status
    raise SolverFailureError(message['error_msg'])
dwave.cloud.exceptions.SolverFailureError: Attempting to run a problem for less than the allowed minimum time_limit 24.75609756097561 s.